import type { Game, GuideItem, Platform, PlatformMeta, ResourceItem, SiteSettings } from "@/lib/types";

const commonDownloads: Game["downloads"] = [
  {
    id: "quark",
    name: "夸克网盘",
    url: "https://pan.quark.cn/",
    recommended: true,
  },
  {
    id: "baidu",
    name: "百度网盘",
    code: "7YXS",
    url: "https://pan.baidu.com/",
  },
  {
    id: "xunlei",
    name: "迅雷云盘",
    code: "ZBC-2026",
    url: "https://pan.xunlei.com/",
  },
  {
    id: "mobile",
    name: "移动云盘",
    url: "https://yun.139.com/",
  },
];

export const platformMeta: PlatformMeta[] = [
  {
    key: "pc",
    label: "电脑游戏",
    shortLabel: "PC",
    description: "高质量单机、独立佳作与大型游戏的免安装资源。",
    filters: [
      "最新游戏",
      "动作冒险",
      "角色扮演",
      "模拟经营",
      "枪战射击",
      "恐怖惊悚",
      "体育竞速",
      "休闲益智",
      "策略战棋",
      "即时战略",
      "模拟器整合",
      "真人影游",
      "联机整合",
    ],
  },
  {
    key: "switch",
    label: "Switch 游戏",
    shortLabel: "NS",
    description: "掌机热门作品、轻松派对与本地多人游戏合集。",
    filters: [
      "switch游戏",
      "音乐",
      "解谜",
      "角色扮演",
      "聚会",
      "经营",
      "策略",
      "竞速",
      "益智",
      "沙盒",
      "模拟",
      "教程",
      "推荐",
      "恐怖",
      "开放世界",
      "射击",
      "多人",
      "回合制",
      "双人",
      "卡牌",
      "动作",
      "剧情",
      "冒险",
      "养成",
      "体育",
      "休闲",
      "互动电影",
      "乙女",
      "NS游戏补全",
    ],
  },
  {
    key: "mobile",
    label: "手机游戏",
    shortLabel: "Mobile",
    description: "精选 Android 与移动端精品，快速查看版本信息。",
    filters: [],
  },
  {
    key: "ps5",
    label: "PS5 游戏",
    shortLabel: "PS5",
    description: "次世代主机大作、动作游戏与沉浸式体验。",
    filters: ["PS5游戏", "exFAT/ffpkg", "ffpfsc"],
  },
  {
    key: "ps4",
    label: "PS4 游戏",
    shortLabel: "PS4",
    description: "经久不衰的主机经典与完整收藏版本。",
    filters: [],
  },
  {
    key: "other",
    label: "其他游戏资源",
    shortLabel: "合集",
    description: "怀旧主机、独立合集与精选游戏资源分享。",
    filters: [],
  },
];

export const games: Game[] = [
  {
    slug: "mistbound-chronicles",
    title: "翼星求生",
    englishTitle: "ICARUS",
    tagline: "降落异星荒野，在严酷环境中建造、狩猎并完成探索任务。",
    platform: "pc",
    category: "动作冒险",
    genre: "开放世界生存",
    size: "70 GB",
    updated: "2026-08-28",
    badge: "新游",
    score: 9.3,
    views: 0,
    featured: true,
    cover: "/covers/mistbound-chronicles.jpg",
    description: [
      "《翼星求生》是一款支持单人及多人合作的 PvE 生存游戏。玩家将降落在地球化失败后的异星荒野，采集资源、建造基地并完成任务。",
      "开放世界模式和阶段任务提供不同节奏的生存体验，天气、野生动物和有限补给都会影响每一次行动。",
    ],
    requirements: {
      minimum: ["Windows 10 64-bit", "Intel Core i5-8400", "16 GB RAM", "GTX 1660 6 GB", "55 GB 可用空间"],
      recommended: ["Windows 10 64-bit", "Intel Core i7-9700", "32 GB RAM", "RTX 3060 Ti", "70 GB 可用空间"],
    },
    downloads: commonDownloads,
  },
  {
    slug: "orbital-echo",
    title: "无人深空",
    englishTitle: "No Man's Sky",
    tagline: "穿越程序生成的浩瀚宇宙，探索星球、建立基地并发现未知生命。",
    platform: "pc",
    category: "动作冒险",
    genre: "太空探索",
    size: "15 GB",
    updated: "2026-08-27",
    badge: "热门",
    score: 8.9,
    views: 0,
    cover: "/covers/orbital-echo.jpg",
    description: ["在几乎无边界的宇宙中自由探索不同生态的星球，采集资源、升级飞船并与各类外星文明互动。", "游戏支持基地建设、舰队管理、多人联机和持续更新的远征内容。"],
    requirements: {
      minimum: ["Windows 10 64-bit", "Intel Core i5-7600", "12 GB RAM", "GTX 1060", "30 GB 可用空间"],
      recommended: ["Windows 11 64-bit", "Intel Core i7-10700", "16 GB RAM", "RTX 3060", "NVMe SSD"],
    },
    downloads: commonDownloads,
  },
  {
    slug: "starharbor-farm",
    title: "星露谷物语",
    englishTitle: "Stardew Valley",
    tagline: "继承一座旧农场，在四季轮转中种植、钓鱼并结识小镇居民。",
    platform: "switch",
    category: "模拟经营",
    genre: "治愈种田",
    size: "880 MB",
    updated: "2026-08-27",
    badge: "新游",
    score: 9.1,
    views: 0,
    featured: true,
    cover: "/covers/starharbor-farm.jpg",
    description: ["从一片荒地开始经营自己的农场，种植作物、饲养动物、探索矿洞并参与小镇节日。", "支持单人体验与多人合作，内容节奏轻松且自由。"],
    downloads: commonDownloads,
  },
  {
    slug: "paperbound-traveler",
    title: "空洞骑士",
    englishTitle: "Hollow Knight",
    tagline: "深入圣巢废墟，在手绘世界中探索洞穴、古城与被遗忘的秘密。",
    platform: "switch",
    category: "动作冒险",
    genre: "类银河战士恶魔城",
    size: "9 GB",
    updated: "2026-08-24",
    badge: "精选",
    score: 8.8,
    views: 0,
    cover: "/covers/paperbound-traveler.jpg",
    description: ["探索相互连通的地下王国，学习新的移动与战斗能力，挑战强敌并寻找隐藏区域。"],
    downloads: commonDownloads,
  },
  {
    slug: "neon-sprint",
    title: "重生细胞",
    englishTitle: "Dead Cells",
    tagline: "在不断变化的城堡中反复挑战，以灵活战斗突破新的区域。",
    platform: "mobile",
    category: "动作冒险",
    genre: "Rogue-lite 动作",
    size: "1.5 GB",
    updated: "2026-08-26",
    badge: "更新",
    score: 8.6,
    views: 0,
    cover: "/covers/neon-sprint.jpg",
    description: ["融合 Rogue-lite、平台动作和探索元素，以快速而精准的战斗在反复变化的关卡中前进。"],
    downloads: commonDownloads,
  },
  {
    slug: "deepblue-diner",
    title: "潜水员戴夫",
    englishTitle: "DAVE THE DIVER",
    tagline: "白天下海捕鱼，夜晚经营寿司店，调查神秘蓝洞背后的故事。",
    platform: "mobile",
    category: "模拟经营",
    genre: "经营冒险",
    size: "10 GB",
    updated: "2026-08-23",
    badge: "热门",
    score: 9.0,
    views: 0,
    featured: true,
    cover: "/covers/deepblue-diner.jpg",
    description: ["白天潜入不断变化的蓝洞收集食材和完成任务，夜晚经营寿司店并研究新的菜谱。"],
    downloads: commonDownloads,
  },
  {
    slug: "red-dune-expedition",
    title: "只狼：影逝二度",
    englishTitle: "Sekiro: Shadows Die Twice",
    tagline: "以义手、忍具与精准拼刀，在战国末期踏上一场复仇之旅。",
    platform: "ps5",
    category: "动作冒险",
    genre: "硬核动作",
    size: "25 GB",
    updated: "2026-08-22",
    badge: "新游",
    score: 9.4,
    views: 0,
    featured: true,
    cover: "/covers/red-dune-expedition.jpg",
    description: ["扮演独臂忍者狼，使用义手忍具、潜行与攻防转换，在高难度战斗中守护自己的主人。"],
    downloads: commonDownloads,
  },
  {
    slug: "moonlit-beacon",
    title: "双人成行",
    englishTitle: "It Takes Two",
    tagline: "为双人合作打造的奇幻冒险，每个章节都有新的玩法与配合方式。",
    platform: "ps5",
    category: "动作冒险",
    genre: "双人合作",
    size: "50 GB",
    updated: "2026-08-20",
    badge: "精选",
    score: 8.7,
    views: 0,
    cover: "/covers/moonlit-beacon.jpg",
    description: ["两位玩家分别扮演科迪和小梅，在不断变化的关卡机制中合作解谜、战斗并修复彼此的关系。"],
    downloads: commonDownloads,
  },
  {
    slug: "windborne-notes",
    title: "荒野大镖客：救赎 2",
    englishTitle: "Red Dead Redemption 2",
    tagline: "跟随亚瑟·摩根与范德林德帮，在时代更迭的美国边境求生。",
    platform: "ps4",
    category: "动作冒险",
    genre: "开放世界",
    size: "150 GB",
    updated: "2026-08-19",
    badge: "更新",
    score: 8.5,
    views: 0,
    cover: "/covers/windborne-notes.jpg",
    description: ["以细腻的开放世界和人物叙事呈现西部时代末期，包含剧情任务、狩猎、探索与营地互动。"],
    downloads: commonDownloads,
  },
  {
    slug: "obsidian-protocol",
    title: "巫师 3：狂猎",
    englishTitle: "The Witcher 3: Wild Hunt",
    tagline: "扮演猎魔人杰洛特，在战火蔓延的大陆追寻希里的下落。",
    platform: "ps4",
    category: "动作冒险",
    genre: "开放世界 RPG",
    size: "50 GB",
    updated: "2026-08-18",
    badge: "热门",
    score: 8.8,
    views: 0,
    cover: "/covers/obsidian-protocol.jpg",
    description: ["在充满支线故事与艰难选择的开放世界中探索、狩猎怪物，并逐步揭开狂猎背后的秘密。"],
    downloads: commonDownloads,
  },
  {
    slug: "iron-embers-collection",
    title: "蔚蓝",
    englishTitle: "Celeste",
    tagline: "帮助玛德琳攀上塞莱斯特山，在精确的平台跳跃中面对内心困境。",
    platform: "other",
    category: "独立游戏",
    genre: "平台跳跃",
    size: "1.2 GB",
    updated: "2026-08-17",
    badge: "精选",
    score: 8.4,
    views: 0,
    cover: "/covers/iron-embers-collection.jpg",
    description: ["以简洁操作和高精度关卡设计构成的独立平台动作游戏，拥有完整剧情与大量可选挑战。"],
    downloads: commonDownloads,
  },
  {
    slug: "glow-archive",
    title: "哈迪斯",
    englishTitle: "Hades",
    tagline: "扮演冥界王子，在一次次逃离中获得诸神赐福并了解家族往事。",
    platform: "other",
    category: "独立游戏",
    genre: "Rogue-like 动作",
    size: "15 GB",
    updated: "2026-08-15",
    badge: "精选",
    score: 8.9,
    views: 0,
    cover: "/covers/glow-archive.jpg",
    description: ["快节奏战斗与持续成长结合，每次逃离都会解锁新的剧情、武器形态和奥林匹斯诸神赐福。"],
    downloads: commonDownloads,
  },
];

export const navItems = [
  { label: "首页", href: "/" },
  ...platformMeta.map((item) => ({ label: item.label, href: `/category/${item.key}` })),
  { label: "MOD / 修改器", href: "/resources?type=mod" },
  { label: "工具 / 补丁", href: "/resources?type=tools" },
  { label: "帮助 / 教程", href: "/help" },
];

export const defaultResources: ResourceItem[] = [
  { id: "controller-bridge", group: "tools", category: "工具软件", name: "手柄映射工具 Controller Bridge", description: "为常见手柄提供按键映射、配置导入和快速切换。", version: "2.4.1", size: "184 MB", updated: "2026-08-27", published: true },
  { id: "runtime-repair", group: "tools", category: "系统软件", name: "游戏运行库检测与修复合集", description: "检测并补齐 DirectX、VC 运行库等常见游戏依赖。", version: "2026.08", size: "1.9 GB", updated: "2026-08-25", published: true },
  { id: "savedock", group: "tools", category: "修改软件", name: "通用存档备份管理器 SaveDock", description: "按游戏建立存档备份、恢复点与迁移记录。", version: "1.8.0", size: "76 MB", updated: "2026-08-23", published: true },
  { id: "frame-monitor", group: "tools", category: "工具软件", name: "帧率与硬件性能监测工具", description: "显示帧率、温度、占用率和帧时间统计。", version: "4.2", size: "244 MB", updated: "2026-08-21", published: true },
  { id: "starter-mod-pack", group: "mod", category: "MOD整合", name: "新手 MOD 整合示例包", description: "用于演示 MOD 资源发布、附件和外链管理流程。", version: "1.0", size: "620 MB", updated: "2026-08-20", published: true },
];

export const defaultGuides: GuideItem[] = [
  { id: "guide-extract", slug: "extract-archives", category: "pc", title: "下载后的压缩包应该如何解压？", summary: "分卷压缩、解压目录和常见报错处理。", content: "建议使用新版 7-Zip 或 WinRAR。将全部分卷放在同一目录，从第一个分卷开始解压；路径尽量只使用英文与数字。", updated: "2026-08-28", published: true },
  { id: "guide-dll", slug: "missing-dll", category: "pc", title: "游戏启动后提示缺少 DLL 文件", summary: "运行库缺失时的安全处理方式。", content: "通常是运行库缺失。请先到工具 / 补丁页面安装 DirectX 与 VC 运行组件，不要单独从陌生网站下载 DLL 文件。", updated: "2026-08-27", published: true },
  { id: "guide-switch-format", slug: "switch-file-format", category: "switch", title: "Switch 游戏格式与版本匹配", summary: "了解资源格式、系统版本和更新顺序。", content: "下载前先核对资源格式和目标系统版本。主程序、更新和 DLC 应按照页面说明的顺序处理，并保留原始文件备份。", updated: "2026-08-26", published: true },
  { id: "guide-mobile-install", slug: "mobile-install", category: "mobile", title: "手机游戏安装与数据包说明", summary: "Android 权限、安装包和数据目录说明。", content: "安装前确认系统版本和剩余空间。若资源包含数据包，请按页面说明放入指定目录，并仅授予运行所需权限。", updated: "2026-08-25", published: true },
  { id: "guide-console-storage", slug: "console-storage", category: "ps5", title: "PS5 存储空间与版本说明", summary: "安装前核对容量与资源版本。", content: "请先检查主机可用空间和资源版本说明。更新前保留存档备份，不要在写入过程中关闭设备。", updated: "2026-08-24", published: true },
  { id: "guide-ps4-update", slug: "ps4-update-order", category: "ps4", title: "PS4 更新顺序与数据管理", summary: "主程序、补丁和存档的处理顺序。", content: "先核对主程序版本，再根据说明应用对应补丁。操作存档前应创建备份，避免版本不匹配造成数据不可用。", updated: "2026-08-23", published: true },
  { id: "guide-other-controller", slug: "other-controller", category: "other", title: "其他平台控制器常见问题", summary: "连接、按键映射与驱动排查。", content: "优先使用系统原生驱动，并在工具页面获取按键映射工具。若按键重复触发，请关闭其他同时运行的映射软件。", updated: "2026-08-22", published: true },
];

export const defaultSiteSettings: SiteSettings = {
  siteName: "ZBC Game",
  announcement: "游戏/软件每日持续更新中",
  contactEmail: "XXXX@XXX.com",
  rightsEmail: "XXX@XXX.com",
};

export function getGame(slug: string) {
  return games.find((game) => game.slug === slug);
}

export function getGamesByPlatform(platform: Platform) {
  return games.filter((game) => game.platform === platform);
}

export function getPlatform(platform: string) {
  return platformMeta.find((item) => item.key === platform);
}

export function searchGames(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return games;
  return games.filter((game) =>
    [game.title, game.englishTitle, game.category, game.genre, game.tagline]
      .join(" ")
      .toLowerCase()
      .includes(normalized),
  );
}

export function formatViews(views: number) {
  if (views >= 10000) return `${(views / 10000).toFixed(1)} 万`;
  return views.toLocaleString("zh-CN");
}
