"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Icon } from "@/components/icon";
import type { FeedbackRecord, Game } from "@/lib/types";

export function FeedbackManager({ initialFeedback, games }: { initialFeedback: FeedbackRecord[]; games: Game[] }) {
  const router = useRouter(); const [items, setItems] = useState(initialFeedback); const [filter, setFilter] = useState<"all" | "pending" | "resolved">("all"); const [notice, setNotice] = useState("");
  const visible = items.filter((item) => filter === "all" || item.status === filter);
  async function update(item: FeedbackRecord, status: FeedbackRecord["status"]) { const response = await fetch(`/api/admin/feedback/${encodeURIComponent(item.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, note: item.note || "" }) }); const result = await response.json() as { data?: FeedbackRecord; error?: string }; if (response.ok && result.data) { setItems((current) => current.map((entry) => entry.id === item.id ? result.data! : entry)); setNotice(status === "resolved" ? "反馈已标记为已处理" : "反馈已重新打开"); router.refresh(); } else setNotice(result.error || "更新失败"); }
  async function remove(item: FeedbackRecord) { if (!window.confirm("删除这条反馈记录吗？")) return; const response = await fetch(`/api/admin/feedback/${encodeURIComponent(item.id)}`, { method: "DELETE" }); if (response.ok) { setItems((current) => current.filter((entry) => entry.id !== item.id)); setNotice("反馈已删除"); router.refresh(); } }
  return <><div className="admin-toolbar"><div className="admin-segmented"><button className={filter === "all" ? "is-active" : ""} type="button" onClick={() => setFilter("all")}>全部 {items.length}</button><button className={filter === "pending" ? "is-active" : ""} type="button" onClick={() => setFilter("pending")}>待处理 {items.filter((item) => item.status === "pending").length}</button><button className={filter === "resolved" ? "is-active" : ""} type="button" onClick={() => setFilter("resolved")}>已处理</button></div></div>{notice && <p className="admin-form-message is-success" role="status">{notice}</p>}<div className="admin-table-wrap"><table className="admin-table admin-table--feedback"><thead><tr><th>反馈</th><th>关联游戏</th><th>提交时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{visible.map((item) => { const game = games.find((entry) => entry.slug === item.gameSlug); return <tr key={item.id}><td><span className={`admin-feedback-type ${item.type === "broken" ? "is-warning" : ""}`}><Icon name={item.type === "broken" ? "warning" : "refresh"} size={15} />{item.type === "broken" ? "资源报错" : "游戏催更"}</span>{item.note && <small>{item.note}</small>}</td><td><strong>{game?.title || item.gameSlug}</strong><small>{item.gameSlug}</small></td><td>{new Date(item.createdAt).toLocaleString("zh-CN")}</td><td><span className={`admin-status ${item.status === "resolved" ? "is-resolved" : "is-pending"}`}>{item.status === "resolved" ? "已处理" : "待处理"}</span></td><td><div className="admin-row-actions">{item.status === "pending" ? <button type="button" onClick={() => update(item, "resolved")}>标记完成</button> : <button type="button" onClick={() => update(item, "pending")}>重新打开</button>}<button className="is-danger" type="button" onClick={() => remove(item)}>删除</button></div></td></tr>; })}</tbody></table>{visible.length === 0 && <div className="admin-empty">暂无反馈记录。</div>}</div></>;
}
