"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Icon } from "@/components/icon";
import { platformMeta } from "@/lib/data";
import type { GuideItem, Platform } from "@/lib/types";

function today() { return new Date().toISOString().slice(0, 10); }
function blankGuide(): GuideItem { return { id: "", slug: "", category: "pc", title: "", summary: "", content: "", updated: today(), published: true }; }

function GuideEditor({ guide, isNew, onClose, onSaved }: { guide: GuideItem; isNew: boolean; onClose: () => void; onSaved: (guide: GuideItem, originalId?: string) => void }) {
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setMessage(""); const data = new FormData(event.currentTarget);
    const payload = { id: data.get("id"), slug: data.get("slug"), category: data.get("category"), title: data.get("title"), summary: data.get("summary"), content: data.get("content"), updated: data.get("updated"), published: data.get("published") === "on" };
    const response = await fetch(isNew ? "/api/admin/guides" : `/api/admin/guides/${encodeURIComponent(guide.id)}`, { method: isNew ? "POST" : "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json() as { data?: GuideItem; error?: string };
    if (!response.ok || !result.data) { setMessage(result.error || "保存失败"); setSaving(false); return; }
    onSaved(result.data, isNew ? undefined : guide.id);
  }
  return <div className="admin-editor-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="admin-editor admin-editor--compact" role="dialog" aria-modal="true" aria-labelledby="guide-editor-title"><header><div><span>{isNew ? "CREATE GUIDE" : "EDIT GUIDE"}</span><h2 id="guide-editor-title">{isNew ? "新增教程" : `编辑：${guide.title}`}</h2><p>教程公开后会显示在帮助中心对应分类下。</p></div><button type="button" aria-label="关闭编辑器" onClick={onClose}><Icon name="x" /></button></header><form onSubmit={submit}><fieldset><legend>教程信息</legend><div className="admin-form-grid"><label>教程标题<input name="title" defaultValue={guide.title} required /></label><label>教程标识<input name="id" defaultValue={guide.id} placeholder="guide-name" required /></label><label>地址标识<input name="slug" defaultValue={guide.slug} placeholder="guide-slug" required /></label><label>教程分类<select name="category" defaultValue={guide.category}>{platformMeta.map((item) => <option value={item.key} key={item.key}>{item.label}问题</option>)}</select></label><label>更新时间<input type="date" name="updated" defaultValue={guide.updated} required /></label><label className="admin-checkbox"><input type="checkbox" name="published" defaultChecked={guide.published} /><span>前台公开显示</span></label></div><label>教程摘要<input name="summary" defaultValue={guide.summary} required /></label><label>教程正文<textarea name="content" rows={12} defaultValue={guide.content} required /></label></fieldset>{message && <p className="admin-form-message is-error" role="alert">{message}</p>}<footer><button className="admin-secondary-button" type="button" onClick={onClose}>取消</button><button className="admin-primary-button" type="submit" disabled={saving}>{saving ? "正在保存…" : "保存教程"}<Icon name="check" size={17} /></button></footer></form></section></div>;
}

export function GuideManager({ initialGuides, initialCreate = false }: { initialGuides: GuideItem[]; initialCreate?: boolean }) {
  const router = useRouter(); const [guides, setGuides] = useState(initialGuides); const [editing, setEditing] = useState<GuideItem | null>(null); const [creating, setCreating] = useState(initialCreate); const [query, setQuery] = useState(""); const [category, setCategory] = useState<"all" | Platform>("all"); const [notice, setNotice] = useState("");
  const filtered = guides.filter((guide) => (category === "all" || guide.category === category) && `${guide.title} ${guide.summary}`.toLowerCase().includes(query.toLowerCase()));
  function saved(guide: GuideItem, originalId?: string) { setGuides((items) => originalId ? items.map((item) => item.id === originalId ? guide : item) : [guide, ...items]); setEditing(null); setCreating(false); setNotice(`${guide.title} 已保存`); router.refresh(); }
  async function remove(guide: GuideItem) { if (!window.confirm(`确定删除“${guide.title}”吗？`)) return; const response = await fetch(`/api/admin/guides/${encodeURIComponent(guide.id)}`, { method: "DELETE" }); if (response.ok) { setGuides((items) => items.filter((item) => item.id !== guide.id)); setNotice(`${guide.title} 已删除`); router.refresh(); } else { const result = await response.json() as { error?: string }; setNotice(result.error || "删除失败"); } }
  return <><div className="admin-toolbar"><label className="admin-search"><Icon name="search" size={18} /><input aria-label="搜索教程" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索教程标题…" /></label><div className="admin-segmented"><button className={category === "all" ? "is-active" : ""} onClick={() => setCategory("all")} type="button">全部</button>{platformMeta.slice(0, 3).map((item) => <button className={category === item.key ? "is-active" : ""} onClick={() => setCategory(item.key)} type="button" key={item.key}>{item.shortLabel}</button>)}</div><button className="admin-primary-button" type="button" onClick={() => setCreating(true)}>新增教程<Icon name="arrow-right" size={17} /></button></div>{notice && <p className="admin-form-message is-success" role="status">{notice}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>教程</th><th>分类</th><th>更新时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.map((guide) => <tr key={guide.id}><td><strong>{guide.title}</strong><small>{guide.summary}</small></td><td>{platformMeta.find((item) => item.key === guide.category)?.label}</td><td>{guide.updated}</td><td><span className={`admin-status ${guide.published ? "is-published" : "is-draft"}`}>{guide.published ? "已发布" : "草稿"}</span></td><td><div className="admin-row-actions"><button type="button" onClick={() => setEditing(guide)}>编辑</button><button className="is-danger" type="button" onClick={() => remove(guide)}>删除</button></div></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="admin-empty">没有匹配的教程。</div>}</div>{creating && <GuideEditor guide={blankGuide()} isNew onClose={() => setCreating(false)} onSaved={saved} />}{editing && <GuideEditor guide={editing} isNew={false} onClose={() => setEditing(null)} onSaved={saved} />}</>;
}
